# Generated by Django 3.2.5 on 2021-08-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libphoto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='est_parta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='parta',
            field=models.CharField(default='', max_length=300),
        ),
    ]
