# Generated by Django 3.2.5 on 2021-08-06 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libphoto', '0002_auto_20210806_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['date'], 'verbose_name': 'Photo'},
        ),
        migrations.AddField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
