# Generated by Django 3.2.5 on 2021-07-13 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date send message')),
                ('mess', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'forum',
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
