# Generated by Django 3.2.5 on 2021-08-14 13:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210713_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPrivateBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date send message')),
                ('mess', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'ForumPrivateBody',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ForumPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('accept', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created forum')),
                ('forum_body', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forum.forumprivatebody')),
            ],
            options={
                'verbose_name': 'Forum Private',
                'ordering': ['date'],
            },
        ),
    ]
