# Generated by Django 3.2.5 on 2021-08-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forumprivate_forumprivatebody'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumprivate',
            name='id_forum',
            field=models.CharField(default='', max_length=50),
        ),
    ]
