# Generated by Django 3.2.5 on 2021-08-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forumprivate_id_forum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumprivate',
            name='forum_body',
        ),
        migrations.AddField(
            model_name='forumprivatebody',
            name='name_forum',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
