# Generated by Django 3.2.5 on 2021-07-31 19:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TimeBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('hours', models.CharField(max_length=20)),
                ('minute', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=200)),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.todolist')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('date_started', models.CharField(max_length=30)),
                ('time_body', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todolist.timebody')),
            ],
        ),
    ]
