# Generated by Django 3.2.5 on 2021-08-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_time_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timebody',
            name='name_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
