# Generated by Django 3.2.5 on 2021-08-01 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_timebody_name_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.timebody'),
        ),
    ]
