# Generated by Django 3.2.5 on 2021-08-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_alter_time_time_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebody',
            name='name_time',
            field=models.CharField(max_length=50),
        ),
    ]
