# Generated by Django 3.2.5 on 2021-08-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_alter_timebody_name_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timebody',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todolist',
            name='time_body_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
