# Generated by Django 3.2.5 on 2021-08-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_auto_20210801_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='timebody',
            name='is_todolist',
            field=models.BooleanField(default=False),
        ),
    ]
