# Generated by Django 3.2 on 2021-09-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0011_auto_20210912_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontimetable',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
