# Generated by Django 3.2.7 on 2021-09-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0012_actiontimetable_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actiontimetable',
            options={'verbose_name': 'Action Time Table'},
        ),
    ]
