# Generated by Django 3.2.5 on 2021-07-14 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date Blog')),
                ('body', models.TextField(max_length=800)),
            ],
            options={
                'verbose_name': 'Blog',
                'ordering': ['date'],
            },
        ),
    ]
