# Generated by Django 3.2.5 on 2021-07-15 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_forumblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumblog',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
