# Generated by Django 3.2.5 on 2021-08-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_forumblog_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='idblog',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
