# Generated by Django 3.2.5 on 2021-09-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiJson', '0002_apijson_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apijson',
            name='body',
            field=models.JSONField(default=dict),
        ),
    ]
