# Generated by Django 3.2.5 on 2021-07-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_forum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
