# Generated by Django 3.2.5 on 2021-07-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_compte_img_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='img_profil',
            field=models.ImageField(default='.', upload_to='./profil_photos'),
        ),
    ]
