# Generated by Django 3.2.5 on 2021-07-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_compte_img_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='id_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
