# Generated by Django 3.2.5 on 2021-07-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_compte_id_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='email',
            field=models.EmailField(default='k', max_length=50),
        ),
    ]
