# Generated by Django 3.2.5 on 2021-08-05 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210730_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Sign Up')),
                ('img_profil', models.ImageField(default='photos/default_img.png', upload_to='photos/')),
            ],
            options={
                'verbose_name': 'profil',
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='Compte',
        ),
    ]
