# Generated by Django 3.2.5 on 2021-08-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210805_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='user',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
