# Generated by Django 3.2.5 on 2021-08-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_profil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='id_name',
            field=models.CharField(default='aaaa', max_length=50),
            preserve_default=False,
        ),
    ]
