# Generated by Django 3.2.5 on 2021-08-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_amie_profil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amie',
        ),
    ]
