# Generated by Django 3.2.5 on 2021-08-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_delete_amie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
