# Generated by Django 3.2.5 on 2021-08-06 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0027_alter_profil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='profil',
            field=models.OneToOneField(default=11, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
