# Generated by Django 3.2.5 on 2021-08-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_profil_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='profil',
            new_name='user',
        ),
    ]
