# Generated by Django 3.2.5 on 2021-08-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_rename_profil_profil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='amie',
            field=models.CharField(default='#', max_length=7525),
        ),
    ]
