# Generated by Django 3.2.5 on 2021-08-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_profil_amie'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='comment',
            field=models.TextField(default='', max_length=200),
        ),
    ]
