# Generated by Django 3.2.5 on 2021-08-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_profil_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='birthdays',
            field=models.CharField(default='non connue', max_length=50),
        ),
        migrations.AddField(
            model_name='profil',
            name='location',
            field=models.CharField(default='non connue', max_length=100),
        ),
        migrations.AddField(
            model_name='profil',
            name='phone',
            field=models.CharField(default='non connue', max_length=50),
        ),
        migrations.AddField(
            model_name='profil',
            name='salary',
            field=models.CharField(default='non connue', max_length=50),
        ),
        migrations.AddField(
            model_name='profil',
            name='title',
            field=models.CharField(default='non connue', max_length=200),
        ),
    ]
