# Generated by Django 3.2.7 on 2021-09-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20210915_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmsg',
            options={'ordering': ['date'], 'verbose_name': 'Group Msg'},
        ),
    ]
