# Generated by Django 3.2.7 on 2021-09-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_groupmsg_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmsg',
            name='messages',
        ),
    ]
